framework:
  asset_mapper:
    # The paths to make available to the asset mapper.
    paths:
      - assets/
    excluded_patterns:
      - '*/assets/styles/_*.scss'
      - '*/assets/styles/**/_*.scss'

symfonycasts_sass:
  root_sass:
    - '%kernel.project_dir%/assets/styles/app.scss'
    - '%kernel.project_dir%/assets/styles/login.scss'