knpu_oauth2_client:
  # configure your clients as described here: https://github.com/knpuniversity/oauth2-client-bundle#configuration
  clients:
    # will create a service: "knpu.oauth2.client.google_main"
    # an instance of: KnpU\OAuth2ClientBundle\Client\Provider\GoogleClient
    google_main:
      # must be "google" - it activates that type!
      type: google
      # add and set these environment variables in your .env files
      client_id: '%env(OAUTH_GOOGLE_CLIENT_ID)%'
      client_secret: '%env(OAUTH_GOOGLE_CLIENT_SECRET)%'
      # a route name you'll create
      redirect_route: !php/const App\Controller\Oauth\GoogleController::ROUTE_LOGGED
      redirect_params: { }
      # Optional value for sending access_type parameter. More detail: https://developers.google.com/identity/protocols/OpenIDConnect#authenticationuriparameters
      # access_type: offline
      # Optional value for sending hd parameter. More detail: https://developers.google.com/identity/protocols/OpenIDConnect#hd-param
      # hosted_domain: null
      # Optional value for additional fields to be requested from the user profile. If set, these values will be included with the defaults. More details: https://developers.google.com/+/web/api/rest/latest/people
      # user_fields: {}
      # whether to check OAuth2 "state": defaults to true
      # use_state: true
